In [4]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

In [5]:
IMAGE_SIZE = 256
CHANNELS = 3

In [6]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True
)
train_generator = train_datagen.flow_from_directory(
        'dataset/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse",
#         save_to_dir="C:\\Code\\potato-disease-classification\\training\\AugmentedImages"
)

Found 1506 images belonging to 3 classes.


In [7]:
train_generator.class_indices

{'Potato___Early_blight': 0, 'Potato___Late_blight': 1, 'Potato___healthy': 2}

In [8]:
class_names = list(train_generator.class_indices.keys())
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [12]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break
#     count+=1
#     if count>2:
#         break

[[[0.66947234 0.6616292  0.7126096 ]
  [0.6698053  0.66196215 0.71294254]
  [0.67013824 0.6622951  0.7132755 ]
  ...
  [0.7132967  0.701532   0.74466926]
  [0.71200746 0.70024276 0.74338   ]
  [0.6957756  0.6840109  0.7271482 ]]

 [[0.67658246 0.6687393  0.7197197 ]
  [0.67358613 0.665743   0.7167234 ]
  [0.67058975 0.6627466  0.71372706]
  ...
  [0.71462846 0.70286375 0.746001  ]
  [0.7113416  0.6995769  0.74271417]
  [0.69411105 0.68234634 0.7254836 ]]

 [[0.70087326 0.6930301  0.7440105 ]
  [0.70120615 0.693363   0.7443434 ]
  [0.7015391  0.69369596 0.74467635]
  ...
  [0.71596014 0.70419544 0.7473327 ]
  [0.7106758  0.6989111  0.7420483 ]
  [0.6924464  0.6806817  0.72381896]]

 ...

 [[0.5812923  0.58521384 0.6048217 ]
  [0.5869276  0.59084916 0.61045706]
  [0.5747837  0.57870525 0.5983131 ]
  ...
  [0.5501589  0.5305511  0.5540805 ]
  [0.5541541  0.53454626 0.55807567]
  [0.55814916 0.5385413  0.5620707 ]]

 [[0.5819582  0.58587974 0.6054876 ]
  [0.58592886 0.5898504  0.60945827]


In [13]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)
validation_generator = validation_datagen.flow_from_directory(
        'dataset/val',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 215 images belonging to 3 classes.


In [14]:
test_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)

test_generator = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 431 images belonging to 3 classes.


In [15]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break

[[[0.725855   0.71801186 0.76899225]
  [0.7638538  0.75601065 0.80699104]
  [0.78408736 0.7762442  0.8272246 ]
  ...
  [0.6067434  0.6028218  0.62242967]
  [0.6152049  0.6112833  0.63089114]
  [0.6236663  0.6197447  0.63935256]]

 [[0.7243835  0.71654034 0.7675207 ]
  [0.7583354  0.7504923  0.80147266]
  [0.7855589  0.77771574 0.82869613]
  ...
  [0.62640035 0.62377775 0.6394888 ]
  [0.61499584 0.61274105 0.62734854]
  [0.6035913  0.6017044  0.61520815]]

 [[0.7229119  0.71506876 0.7660492 ]
  [0.7528171  0.74497396 0.79595435]
  [0.78703046 0.7791873  0.8301677 ]
  ...
  [0.5028046  0.5028046  0.5106477 ]
  [0.49066427 0.49066427 0.4985074 ]
  [0.47852397 0.47852397 0.4863671 ]]

 ...

 [[0.79215693 0.7803922  0.8078432 ]
  [0.79215693 0.7803922  0.8078432 ]
  [0.79215693 0.7803922  0.8078432 ]
  ...
  [0.67586815 0.66410345 0.6915544 ]
  [0.7151486  0.7033839  0.7308349 ]
  [0.69164765 0.6798829  0.7073339 ]]

 [[0.7940438  0.7822791  0.80973005]
  [0.79441166 0.78264695 0.81009793]


In [16]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 127, 127, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 64)        0

In [18]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [19]:
history = model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20,
)

Epoch 1/20
47/47 [==============================] - 103s 2s/step - loss: 0.8838 - accuracy: 0.5149 - val_loss: 0.7811 - val_accuracy: 0.6615
Epoch 2/20
47/47 [==============================] - 86s 2s/step - loss: 0.6099 - accuracy: 0.7368 - val_loss: 0.4491 - val_accuracy: 0.8073
Epoch 3/20
47/47 [==============================] - 88s 2s/step - loss: 0.3946 - accuracy: 0.8504 - val_loss: 0.4334 - val_accuracy: 0.8073
Epoch 4/20
47/47 [==============================] - 87s 2s/step - loss: 0.3091 - accuracy: 0.8745 - val_loss: 0.3425 - val_accuracy: 0.8646
Epoch 5/20
47/47 [==============================] - 84s 2s/step - loss: 0.3015 - accuracy: 0.8772 - val_loss: 0.2623 - val_accuracy: 0.8750
Epoch 6/20
47/47 [==============================] - 85s 2s/step - loss: 0.2116 - accuracy: 0.9111 - val_loss: 0.3362 - val_accuracy: 0.8594
Epoch 7/20
47/47 [==============================] - 85s 2s/step - loss: 0.1814 - accuracy: 0.9294 - val_loss: 0.2247 - val_accuracy: 0.9219
Epoch 8/20
47/47 [=